backend:
  name: github
  repo: jvarness/next-with-bulma
  branch: blog
media_folder: static/img
collections:
  - name: "blog"
    label: "Blog"
    folder: "/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
